**LEITURA DOS DADOS DO CSV DATA_BOTTOM**

In [8]:
import pandas as pd

data_bottom = pd.read_csv("../data/output_bottom.csv", sep=",")

data_bottom.head()

sAddress       rAddress              sMACs              rMACs  \
0  198.18.134.11  198.18.134.12  b8:27:eb:6d:4f:4b  b8:27:eb:5b:50:19   
1  198.18.134.12  198.18.134.31  b8:27:eb:5b:50:19  b8:27:eb:3e:5d:96   
2  198.18.134.11  198.18.134.31  b8:27:eb:6d:4f:4b  b8:27:eb:3e:5d:96   
3  198.18.134.11  198.18.134.15  b8:27:eb:6d:4f:4b  b8:27:eb:15:88:9c   
4  198.18.134.12  198.18.134.15  b8:27:eb:5b:50:19  b8:27:eb:15:88:9c   

            sIPs           rIPs  protocol                   startDate  \
0  198.18.134.11  198.18.134.12  IPV4-TCP  2023-03-10 10:29:34.085540   
1  198.18.134.12  198.18.134.31  IPV4-TCP  2023-03-10 10:29:34.090079   
2  198.18.134.11  198.18.134.31  IPV4-TCP  2023-03-10 10:29:34.160288   
3  198.18.134.11  198.18.134.15  IPV4-TCP  2023-03-10 10:29:34.416492   
4  198.18.134.12  198.18.134.15  IPV4-TCP  2023-03-10 10:29:34.425676   

                      endDate         start  ...  sAckDelayMax  rAckDelayMax  \
0  2023-03-10 10:29:34.565764  1.678441e+09  ...         0.198         0.200   
1  2023-03-10 10:29:34.500119  1.678441e+09  ...         0.195         0.001   
2  2023-03-10 10:29:34.623275  1.678441e+09  ...         0.190         0.001   
3  2023-03-10 10:29:34.916407  1.678441e+09  ...         0.001         0.491   
4  2023-03-10 10:29:34.925551  1.678441e+09  ...         0.000         0.496   

   sAckDelayMin  rAckDelayMin  sAckDelayAvg  rAckDelayAvg  IT_B_Label  \
0           0.0           0.0      0.020279      0.028912           0   
1           0.0           0.0      0.020338      0.000455           0   
2           0.0           0.0      0.015988      0.000537           0   
3           0.0           0.0      0.000578      0.048820           0   
4           0.0           0.0      0.000423      0.077478           0   

   IT_M_Label  NST_B_Label  NST_M_Label  
0      Normal            0       Normal  
1      Normal            0       Normal  
2      Normal            0       Normal  
3      Normal            0       Normal  
4      Normal            0       Normal  

[5 rows x 64 columns]

In [9]:
data_bottom.shape

(55425, 64)

**LIMPEZA DO DATASET - REMOÇÃO DE COLUNAS NULAS**

In [10]:
data_bottom.nunique()

sAddress          34
rAddress          18
sMACs             20
rMACs             16
sIPs              21
                ... 
rAckDelayAvg    8751
IT_B_Label         2
IT_M_Label         8
NST_B_Label        2
NST_M_Label        8
Length: 64, dtype: int64

In [11]:
data_bottom.isnull().sum()

sAddress           0
rAddress           0
sMACs              0
rMACs              0
sIPs            3855
                ... 
rAckDelayAvg    7511
IT_B_Label         0
IT_M_Label         0
NST_B_Label        0
NST_M_Label        0
Length: 64, dtype: int64

In [12]:
data_bottom = data_bottom.dropna(subset=["rAckDelayAvg", "sInterPacketAvg", "sIPs", "rInterPacketAvg", "sAckDelayMax", "sAckDelayMin", "sAckDelayAvg"])

In [13]:
data_bottom.isnull().value_counts()

sAddress  rAddress  sMACs  rMACs  sIPs   rIPs   protocol  startDate  endDate  start  end    startOffset  endOffset  duration  sPackets  rPackets  sBytesSum  rBytesSum  sBytesMax  rBytesMax  sBytesMin  rBytesMin  sBytesAvg  rBytesAvg  sLoad  rLoad  sPayloadSum  rPayloadSum  sPayloadMax  rPayloadMax  sPayloadMin  rPayloadMin  sPayloadAvg  rPayloadAvg  sInterPacketAvg  rInterPacketAvg  sttl   rttl   sAckRate  rAckRate  sUrgRate  rUrgRate  sFinRate  rFinRate  sPshRate  rPshRate  sSynRate  rSynRate  sRstRate  rRstRate  sWinTCP  rWinTCP  sFragmentRate  rFragmentRate  sAckDelayMax  rAckDelayMax  sAckDelayMin  rAckDelayMin  sAckDelayAvg  rAckDelayAvg  IT_B_Label  IT_M_Label  NST_B_Label  NST_M_Label
False     False     False  False  False  False  False     False      False    False  False  False        False      False     False     False     False      False      False      False      False      False      False      False      False  False  False        False        False        False       

**CONVERSÃO DE FEATURES SIMBÓLICAS PARA FEATURES NUMÉRICAS**

In [14]:
data_bottom["sAddress"].replace(["198.18.134.11", "198.18.134.12", "198.18.134.6", "198.18.134.38", "198.18.134.40", "198.18.134.47", "198.18.134.49"], [0, 1, 2, 3, 4, 5, 6], inplace=True)
data_bottom["sAddress"].unique()

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
data_bottom["rAddress"].replace(['198.18.134.12', '198.18.134.31', '198.18.134.15', '198.18.134.99'], [0, 1, 2, 3], inplace=True)
data_bottom["rAddress"].unique()

array([0, 1, 2, 3])

In [16]:
data_bottom["sMACs"].replace(['b8:27:eb:6d:4f:4b', 'b8:27:eb:5b:50:19', '00:07:7c:8c:43:63'], [0, 1, 2], inplace=True)
data_bottom["sMACs"].unique()

array([0, 1, 2])

In [17]:
data_bottom["rMACs"].replace(['b8:27:eb:5b:50:19', 'b8:27:eb:3e:5d:96', 'b8:27:eb:15:88:9c',
       'b8:27:eb:d1:b7:ef', 'b8:27:eb:d1:b7:ef/b8:27:eb:15:88:9c',
       '00:07:7c:88:6e:83/00:24:9b:6d:b8:89', '00:24:9b:6d:b8:89'], [0, 1, 2, 3, 4, 5, 6], inplace=True)
data_bottom["rMACs"].unique()

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
data_bottom["sIPs"].replace(['198.18.134.11', '198.18.134.12', '198.18.134.6', '198.18.134.38',
       '198.18.134.40', '198.18.134.47', '198.18.134.49'], [0, 1, 2, 3, 4, 5, 6], inplace=True)
data_bottom["sIPs"].unique()

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
data_bottom["rIPs"].replace(['198.18.134.12', '198.18.134.31', '198.18.134.15', '198.18.134.99'], [0, 1, 2, 3], inplace=True)
data_bottom["rIPs"].unique()

array([0, 1, 2, 3])

In [20]:
data_bottom["protocol"].replace(['IPV4-TCP'], [0], inplace=True)
data_bottom["protocol"].unique()

array([0])

In [21]:
data_bottom["IT_M_Label"].replace(['Normal', 'BAD-MITM', 'BAD-MISCONF-DUPLICATION', 'BAD-SSH',
       'GOOD-SSH', 'BAD-PORTSCAN1', 'BAD-MISCONF', 'BAD-PORTSCAN2'], [0, 1, 1, 1, 1, 1, 1, 1], inplace=True)
data_bottom["IT_M_Label"].unique()

array([0, 1])

In [22]:
data_bottom["NST_M_Label"].replace(['Normal', 'BAD-MITM', 'BAD-MISCONF-DUPLICATION', 'BAD-SSH',
       'BAD-MISCONF', 'GOOD-SSH'], [0, 1, 1, 1, 1, 1], inplace=True)
data_bottom["NST_M_Label"].unique()

array([0, 1])

**UTILIZAÇÃO DE ONE HOT ENCODING PARA AS FEATURES SIMBÓLICAS**

In [23]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

colunas_categoricas = ['sAddress', 'rAddress', 'rIPs', 'sIPs', 'sMACs', 'rMACs', 'protocol']

one_hot_enc = make_column_transformer(
    (OneHotEncoder(handle_unknown = 'ignore'),
    colunas_categoricas),
    remainder='passthrough')

dados = one_hot_enc.fit_transform(data_bottom)
dados = pd.DataFrame(dados, columns=one_hot_enc.get_feature_names_out())
dados = dados.drop(['remainder__startDate', 'remainder__endDate'], axis=1)
dados

onehotencoder__sAddress_0 onehotencoder__sAddress_1  \
0                           1.0                       0.0   
1                           0.0                       1.0   
2                           1.0                       0.0   
3                           1.0                       0.0   
4                           0.0                       1.0   
...                         ...                       ...   
47734                       1.0                       0.0   
47735                       0.0                       1.0   
47736                       0.0                       0.0   
47737                       0.0                       0.0   
47738                       0.0                       0.0   

      onehotencoder__sAddress_2 onehotencoder__sAddress_3  \
0                           0.0                       0.0   
1                           0.0                       0.0   
2                           0.0                       0.0   
3                           0.0                       0.0   
4                           0.0                       0.0   
...                         ...                       ...   
47734                       0.0                       0.0   
47735                       0.0                       0.0   
47736                       1.0                       0.0   
47737                       0.0                       1.0   
47738                       0.0                       0.0   

      onehotencoder__sAddress_4 onehotencoder__sAddress_5  \
0                           0.0                       0.0   
1                           0.0                       0.0   
2                           0.0                       0.0   
3                           0.0                       0.0   
4                           0.0                       0.0   
...                         ...                       ...   
47734                       0.0                       0.0   
47735                       0.0                       0.0   
47736                       0.0                       0.0   
47737                       0.0                       0.0   
47738                       1.0                       0.0   

      onehotencoder__sAddress_6 onehotencoder__rAddress_0  \
0                           0.0                       1.0   
1                           0.0                       0.0   
2                           0.0                       0.0   
3                           0.0                       0.0   
4                           0.0                       0.0   
...                         ...                       ...   
47734                       0.0                       0.0   
47735                       0.0                       0.0   
47736                       0.0                       0.0   
47737                       0.0                       0.0   
47738                       0.0                       0.0   

      onehotencoder__rAddress_1 onehotencoder__rAddress_2  ...  \
0                           0.0                       0.0  ...   
1                           1.0                       0.0  ...   
2                           1.0                       0.0  ...   
3                           0.0                       1.0  ...   
4                           0.0                       1.0  ...   
...                         ...                       ...  ...   
47734                       0.0                       1.0  ...   
47735                       0.0                       1.0  ...   
47736                       0.0                       0.0  ...   
47737                       0.0                       0.0  ...   
47738                       0.0                       0.0  ...   

      remainder__sAckDelayMax remainder__rAckDelayMax remainder__sAckDelayMin  \
0                       0.198                     0.2                     0.0   
1                       0.195                   0.001                     0.0   
2                        0.19         

In [24]:
for column in dados.columns:
    print(column)

onehotencoder__sAddress_0
onehotencoder__sAddress_1
onehotencoder__sAddress_2
onehotencoder__sAddress_3
onehotencoder__sAddress_4
onehotencoder__sAddress_5
onehotencoder__sAddress_6
onehotencoder__rAddress_0
onehotencoder__rAddress_1
onehotencoder__rAddress_2
onehotencoder__rAddress_3
onehotencoder__rIPs_0
onehotencoder__rIPs_1
onehotencoder__rIPs_2
onehotencoder__rIPs_3
onehotencoder__sIPs_0
onehotencoder__sIPs_1
onehotencoder__sIPs_2
onehotencoder__sIPs_3
onehotencoder__sIPs_4
onehotencoder__sIPs_5
onehotencoder__sIPs_6
onehotencoder__sMACs_0
onehotencoder__sMACs_1
onehotencoder__sMACs_2
onehotencoder__rMACs_0
onehotencoder__rMACs_1
onehotencoder__rMACs_2
onehotencoder__rMACs_3
onehotencoder__rMACs_4
onehotencoder__rMACs_5
onehotencoder__rMACs_6
onehotencoder__protocol_0
remainder__start
remainder__end
remainder__startOffset
remainder__endOffset
remainder__duration
remainder__sPackets
remainder__rPackets
remainder__sBytesSum
remainder__rBytesSum
remainder__sBytesMax
remainder__rBytes

**IMPORTAÇÃO DE BIBLIOTECAS E PRÉ-PROCESSAMENTO DOS DADOS**

In [25]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

target = "remainder__IT_B_Label"

# Extrair features e rótulos do DataFrame
X = dados.drop(target, axis=1).values
y = dados[target].values

X = X.astype('float32')
y = y.astype('float32')

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizar os dados (opcional, dependendo da natureza dos seus dados)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Definir o modelo
model = Sequential()
model.add(Dense(100, activation='relu', input_shape=(87,)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='softmax'))  # Linear activation para tarefa de regressão

# Compilar o modelo
opt = SGD(learning_rate=0.01, momentum=0.9)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

# Treinar o modelo
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

# Avaliar o modelo no conjunto de teste
test_loss, test_acc = model.evaluate(X_test, y_test)


Epoch 1/5


/home/joaobatista/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py:1176: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


538/538 [==============================] - 6s 5ms/step - loss: 0.0000e+00 - accuracy: 0.6248 - val_loss: 0.0000e+00 - val_accuracy: 0.6419
Epoch 2/5
538/538 [==============================] - 2s 5ms/step - loss: nan - accuracy: 0.4812 - val_loss: nan - val_accuracy: 0.3581
Epoch 3/5
538/538 [==============================] - 3s 5ms/step - loss: nan - accuracy: 0.3752 - val_loss: nan - val_accuracy: 0.3581
Epoch 4/5
538/538 [==============================] - 2s 4ms/step - loss: nan - accuracy: 0.3752 - val_loss: nan - val_accuracy: 0.3581
Epoch 5/5
299/299 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.3665


In [26]:
import os
# Make TensorFlow logs less verbose
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import flwr as fl
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D,Flatten,Dense
from tensorflow.keras.optimizers import SGD
import numpy as np
import ray
from matplotlib import pyplot as plt

In [65]:
def define_model(input_shape,num_classes):
  model = Sequential()
  model.add(Dense(100, activation='relu', input_shape=input_shape))
  model.add(Dropout(0.5))
  model.add(Dense(num_classes, activation='relu'))  # Linear activation para tarefa de regressão
  model.add(Flatten())
  # compile model
  opt = SGD(learning_rate=0.01, momentum=0.9)
  model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [66]:
input_shape = (87,)
num_classes = 2

model = define_model(input_shape,num_classes)

In [67]:
X = dados.drop(target, axis=1).values
y = dados[target].values

X = X.astype('float32')
y = y.astype('float32')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [68]:
batch_size = 64
epochs = 5
history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    validation_split=0.1)

Epoch 1/5
538/538 [==============================] - 4s 6ms/step - loss: 7.7965 - accuracy: 0.5803 - val_loss: 7.6810 - val_accuracy: 0.6419
Epoch 2/5
538/538 [==============================] - 2s 3ms/step - loss: 7.8036 - accuracy: 0.5829 - val_loss: 7.6810 - val_accuracy: 0.6419
Epoch 3/5
538/538 [==============================] - 3s 6ms/step - loss: 7.8295 - accuracy: 0.5774 - val_loss: 7.6810 - val_accuracy: 0.6419
Epoch 4/5
538/538 [==============================] - 3s 6ms/step - loss: 7.8565 - accuracy: 0.5764 - val_loss: 7.6810 - val_accuracy: 0.6419
Epoch 5/5
538/538 [==============================] - 3s 5ms/step - loss: 7.8314 - accuracy: 0.5773 - val_loss: 7.6810 - val_accuracy: 0.6419
